package printing

import (
	"embed"
	"encoding/base64"
	"html/template"
	"io"
	"strings"
	"time"

	"einvoicing/internal/brand"
	"einvoicing/internal/domain"
	"einvoicing/internal/store"
	"einvoicing/internal/tax"

	"github.com/shopspring/decimal"
)

//go:embed templates/*.html
var tplFS embed.FS

var templates = template.Must(template.New("").ParseFS(tplFS, "templates/*.html"))

// Options controls rendering.
type Options struct {
	Format      string // "a4" (default) or "thermal"
	AutoPrint   bool
	ShowToolbar bool
	Duplicate   bool   // print "DUPLICATE" copy label
	Nonce       string // CSP nonce for the page's only script
	CompanyLogo []byte // raw image
	CompanyMime string
	FBRLogo     []byte // official FBR DI logo uploaded by the user
	FBRLogoMime string
	Now         time.Time
}

type line struct {
	No                                            int
	Description, HSCode, SaleType, SRO, UoM, Rate string
	Qty, UnitPrice, Discount, Value, Retail       string
	SalesTax, FurtherTax, ExtraTax, FED, Total    string
}

type totals struct {
	Value, Retail, SalesTax, FurtherTax, ExtraTax, FED, Total, Withheld, Payable string
}

type rateRow struct{ SaleType, Rate, Value, SalesTax string }

type cols struct{ Discount, Retail, Further, Extra, FED, Withheld bool }

type view struct {
	Title, InvoiceDate, Watermark, Notice, CopyLabel, AmountWords, PrintedAt, ProductName, ShortSeal string
	FBRNumber, Nonce                                                                                 string
	Company                                                                                          *store.Company
	Invoice                                                                                          *store.Invoice
	Settings                                                                                         store.PrintSettings
	CompanyLogo, FBRLogo                                                                             template.URL
	QR                                                                                               template.HTML
	Lines                                                                                            []line
	Rates                                                                                            []rateRow
	T                                                                                                totals
	Cols                                                                                             cols
	IsDebitNote, AutoPrint, ShowToolbar                                                              bool
	Sheets                                                                                           []sheet
}

// sheet is one printed copy of the A4 invoice; CopyLabel shadows the view's.
type sheet struct {
	*view
	CopyLabel string
}

// copyNames label the copies when more than one is printed per invoice.
var copyNames = []string{"BUYER'S COPY", "SELLER'S COPY", "OFFICE COPY", "COPY 4", "COPY 5"}

func dataURI(b []byte, mime string) template.URL {
	if len(b) == 0 {
		return ""
	}
	if mime == "" {
		mime = "image/png"
	}
	// Only image types are embedded (prevents script injection via data URIs).
	if !strings.HasPrefix(mime, "image/") {
		return ""
	}
	return template.URL("data:" + mime + ";base64," + base64.StdEncoding.EncodeToString(b))
}

func amt(d decimal.Decimal) string { return tax.FormatAmount(d) }

// Render writes the printable invoice HTML.
func Render(w io.Writer, c *store.Company, inv *store.Invoice, o Options) error {
	if o.Now.IsZero() {
		o.Now = time.Now()
	}
	v := view{Company: c, Invoice: inv, Settings: c.PrintSettings, AutoPrint: o.AutoPrint, ShowToolbar: o.ShowToolbar, Nonce: o.Nonce,
		ProductName: brand.ProductName, IsDebitNote: inv.DocType == domain.DocDebitNote}
	v.Title = "SALES TAX INVOICE"
	if v.IsDebitNote {
		v.Title = "DEBIT NOTE"
	}
	if d, err := time.Parse("2006-01-02", inv.InvoiceDate); err == nil {
		v.InvoiceDate = d.Format("02-Jan-2006")
	} else {
		v.InvoiceDate = inv.InvoiceDate
	}
	loc, _ := time.LoadLocation("Asia/Karachi")
	if loc == nil {
		loc = time.FixedZone("PKT", 5*3600)
	}
	v.PrintedAt = o.Now.In(loc).Format("02-Jan-2006 15:04")
	if o.Duplicate || inv.PrintCount > 0 {
		v.CopyLabel = "DUPLICATE"
	}
	v.CompanyLogo = dataURI(o.CompanyLogo, o.CompanyMime)
	v.FBRLogo = dataURI(o.FBRLogo, o.FBRLogoMime)

	reported := inv.Status == domain.StatusAccepted || inv.Status == domain.StatusCancelled
	if reported && inv.FBRInvoiceNumber != "" {
		v.FBRNumber = inv.FBRInvoiceNumber
		if svg, err := QRSVG(inv.FBRInvoiceNumber); err == nil {
			v.QR = template.HTML(svg) // generated by us, contains no user input other than the FBR number
		}
	}
	switch {
	case inv.Status == domain.StatusCancelled:
		v.Watermark = "CANCELLED"
		v.Notice = "This invoice was cancelled on " + inv.CancelledAt + " — " + inv.CancelReason
	case !reported:
		v.Watermark = "DRAFT — NOT REPORTED TO FBR"
		v.Notice = "Not a valid sales tax invoice: it has not been reported to FBR Digital Invoicing (status " + string(inv.Status) + ")."
	case inv.Environment == domain.EnvSandbox:
		v.Watermark = "FBR SANDBOX — NOT A VALID TAX INVOICE"
	case inv.Environment == domain.EnvSimulator:
		v.Watermark = "TRAINING — NOT A VALID TAX INVOICE"
	}

	style := tax.WordsSouthAsian
	if c.PrintSettings.WordsStyle == string(tax.WordsInternational) {
		style = tax.WordsInternational
	}
	payable := inv.Totals.AmountPayable
	v.AmountWords = tax.AmountInWords(payable, style)
	if len(inv.SealHash) >= 16 {
		v.ShortSeal = inv.SealHash[:16]
	}

	for _, it := range inv.Items {
		l := line{No: it.LineNo, Description: it.Description, HSCode: it.HSCode, SaleType: it.SaleType, UoM: it.UoM, Rate: it.Rate,
			Qty: tax.FormatQty(it.Quantity), UnitPrice: amt(it.UnitPrice), Discount: amt(it.Discount), Value: amt(it.ValueExclST),
			Retail: amt(it.RetailValue), SalesTax: amt(it.SalesTax), FurtherTax: amt(it.FurtherTax), ExtraTax: amt(it.ExtraTax),
			FED: amt(it.FED), Total: amt(it.TotalValue)}
		if it.SROScheduleNo != "" {
			l.SRO = it.SROScheduleNo
			if it.SROItemSerialNo != "" {
				l.SRO += " S.No. " + it.SROItemSerialNo
			}
		}
		if it.UnitPrice.IsZero() && it.Quantity.IsPositive() {
			l.UnitPrice = amt(it.ValueExclST.Add(it.Discount).Div(it.Quantity))
		}
		v.Lines = append(v.Lines, l)
		v.Cols.Discount = v.Cols.Discount || (it.Discount.IsPositive() && c.PrintSettings.ShowDiscount)
		v.Cols.Retail = v.Cols.Retail || it.RetailValue.IsPositive()
		v.Cols.Further = v.Cols.Further || it.FurtherTax.IsPositive()
		v.Cols.Extra = v.Cols.Extra || it.ExtraTax.IsPositive()
		v.Cols.FED = v.Cols.FED || it.FED.IsPositive()
		v.Cols.Withheld = v.Cols.Withheld || it.STWithheld.IsPositive()
	}
	t := inv.Totals
	v.T = totals{Value: amt(t.ValueExclST), Retail: amt(t.RetailValue), SalesTax: amt(t.SalesTax), FurtherTax: amt(t.FurtherTax),
		ExtraTax: amt(t.ExtraTax), FED: amt(t.FED), Total: amt(t.TotalValue), Withheld: amt(t.STWithheld), Payable: amt(t.AmountPayable)}

	// Rate summary.
	idx := map[string]int{}
	type acc struct {
		st, rate   string
		val, stTax decimal.Decimal
	}
	var accs []*acc
	for _, it := range inv.Items {
		k := it.SaleType + "|" + it.Rate
		i, ok := idx[k]
		if !ok {
			i = len(accs)
			idx[k] = i
			accs = append(accs, &acc{st: it.SaleType, rate: it.Rate})
		}
		accs[i].val = accs[i].val.Add(it.ValueExclST)
		accs[i].stTax = accs[i].stTax.Add(it.SalesTax)
	}
	for _, a := range accs {
		v.Rates = append(v.Rates, rateRow{SaleType: a.st, Rate: a.rate, Value: amt(a.val), SalesTax: amt(a.stTax)})
	}

	copies := c.PrintSettings.Copies
	if copies < 1 {
		copies = 1
	}
	if copies > len(copyNames) {
		copies = len(copyNames)
	}
	if copies == 1 {
		v.Sheets = []sheet{{view: &v, CopyLabel: v.CopyLabel}}
	} else {
		for i := 0; i < copies; i++ {
			label := copyNames[i]
			if v.CopyLabel != "" {
				label = v.CopyLabel + " · " + label
			}
			v.Sheets = append(v.Sheets, sheet{view: &v, CopyLabel: label})
		}
	}

	name := "invoice_a4.html"
	if o.Format == "thermal" || (o.Format == "" && c.PrintSettings.PaperSize == "thermal80") {
		name = "invoice_thermal.html"
	}
	return templates.ExecuteTemplate(w, name, &v)
}
